#!/usr/bin/env bash
# Script that displays information about subdomains.
# shellcheck disable=SC2086
subdomain_info ()
{
    dig_result=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ')
    echo "$2 $dig_result" | awk '{print "The subdomain " $1 " is a " $8 " record and points to " $9}'
}
if [ $# -eq 1 ]
then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        subdomain_info $1 $subdomain
    done
else
        subdomain_info $1 $2
fi
