#!/usr/bin/env bash
#script transfers a file from our client to a server.
if [ "$#" -ne 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

path="$1"
ip="$2"
username="$3"
ssh_privkey="$4"

#scp -i school -o StrictHostKeyChecking=no somepage.html ubuntu@54.87.180.247:~
scp -i "$ssh_privkey" -o StrictHostKeyChecking=no "$path" "$username"@"$ip":~
