#!/usr/bin/env bash
# Update package information and install nginx
# shellcheck disable=SC2181
sudo apt update
sudo apt install nginx -y

# Configure Nginx
# This is a "here document", the << starts the here document. The EOF is the
# marker and it signifies where the "here doc" begins and end, I have chosen
# to use EOF. The here document is fed to the 'cat' command in this case.
# 'cat' output is fed to the 'tee' command which puts the lines into the file
# while optionally displaying it on the terminal
# /dev/null suppresses any output to the terminal
cat <<EOF | tee /etc/nginx/sites-available/helloworld > /dev/null
server {
    listen 80;
    server_name 54.87.180.247;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

# Create symbolic link and reload Nginx
sudo ln -s /etc/nginx/sites-available/helloworld /etc/nginx/sites-enabled/
sudo nginx -t  # Test configuration syntax
if [ $? -eq 0 ]
then
    service nginx reload  # Reload Nginx if configuration is valid
    #echo "Nginx configuration reloaded."
    #else
    #echo "Nginx configuration test failed. Please fix the configuration and reload manually."
fi
