#!/usr/bin/env bash
# Update package information and install nginx
# shellcheck disable=SC2154
sudo apt update
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo cat <<EOF | sudo tee /etc/nginx/sites-available/index.html > /dev/null
server {
    listen 80;
    root /var/www/html;
    index index.html

    server_name 54.87.180.247;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF
sudo ln -s /etc/nginx/sites-available/index.html /etc/nginx/sites-enabled/index.html
sudo service nginx reload
sudo curl 127.0.0.1
