#!/usr/bin/env bash
# Redirects a page
sudo apt update -y
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Configure Nginx
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.yahoo.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
