#!/usr/bin/env bash
# Redirects a page
sudo apt update -y
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx
sudo cat <<EOF | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null
server {
    listen 80;
    server_name your_ip_address;

    location /redirect_me {
        return 301 https://youtube.com;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me
sudo service nginx restart
