#!/usr/bin/env bash
# redirects a page
sudo apt update -y
sudo apt install nginx -y

# Configure Nginx
sudo cat <<EOF | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null
server {
    listen 80;

    server_name 54.87.180.247;

    location /redirect_me {
        return 301 https://youtube.com;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me
sudo service nginx restart
