#!/usr/bin/env bash
# 404 page

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.yahoo.com permanent;\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation /custom_404.html {\n\tinternal;\n}\n' /etc/nginx/sites-availabl
e/default

service nginx restart
