#!/usr/bin/env bash
# 404 page

sudo apt update -y
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
#configure nginx
sudo sed -i '/listen 80 default_server;/a \trewrite ^/redirect_me https://www.yahoo.com permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a \terror_page 404 /custom_404.html;\nlocation /custom_404.html {\n\tinternal;\n}\n' /etc/nginx/sites-available/default

sudo service nginx restart
