#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

sudo apt update -y
suod apt install nginx -y
service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.yahoo.com permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
