#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

sudo apt update -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me https://www.yahoo.com permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
