#!/usr/bin/env bash
# Configures a HAproxy load-balancer
sudo apt update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get install haproxy=2.4.\* -y
sudo cp sam.cfg sam.cfg.bak
sudo sed -i -e '\#errorfile 504 /etc/haproxy/errors/504.http# {
   a\
\nfrontend http
}' /etc/haproxy/haproxy.cfg
sudo sed -i '/frontend http/a  \ \ bind *:80' /etc/haproxy/haproxy.cfg
sudo sed -i '/bind \*:80/a  \ \ tmode http' /etc/haproxy/haproxy.cfg
sudo sed -i '/mode http/a  \ \ default_backend web_backend' /etc/haproxy/haproxy.cfg
sudo sed -i '/default_backend web_backend/a backend web_backend' /etc/haproxy/haproxy.cfg
sudo sed -i '/^backend web_backend$/a  \ \ balance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '/balance roundrobin/a   \ \ server 74697-web-01 54.87.180.247:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/server 74697-web-01 54.87.180.247:80 check/a   \ \ server 74697-web-02 34.227.101.14:80 check' /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy.service
