#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

MYSQL_ROOT_PASSWORD="$1"

# Get the current date in the desired format (day-month-year)
DATE=$(date +%d-%m-%Y)

# Define the dump file name
DUMP_FILE="backup.sql"

# Define the archive file name
ARCHIVE_FILE="$DATE.tar.gz"

# Perform MySQL dump with root user and specified password
mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > "$DUMP_FILE"

# Compress the dump file into a tar.gz archive
tar -czvf "$ARCHIVE_FILE" "$DUMP_FILE"

# Clean up the dump file
#rm "$DUMP_FILE"

exit 0
