#!/usr/bin/env bash
# messes /etc/hosts
cp /etc/hosts ~/hosts.new
#sed -i s/^127.*$// ~/hosts.new
sed -i s/127.0.0.2( |\t){1,10}localhost( |\t){0,10}$// ~/hosts.new
sed -i s/^8.8.8.8( |\t){1,10}facebook.com( |\t){0,10}$//*$// ~/hosts.new
cp -f ~/hosts.new /etc/hosts
